### ISSUE TITLE
Failed to load a language-casetalk package grammar

### ISSUE THREAD

**Issue by bcp-software** [deltiq-developer/language-casetalk#4]
Starting ATOM results in an error dialog:

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [language-casetalk](https://github.com/deltiq-developer/language-casetalk) package 0.3.1

### Stack Trace

Failed to load a language-casetalk package grammar

```
At Cannot find module './build/Release/tree_sitter_CaseTalk_binding'
Require stack:
- /Users/marcowobben 1/.atom/packages/language-casetalk/node_modules/tree-sitter-casetalk/index.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html in /Users/marcowobben 1/.atom/packages/language-casetalk/grammars/tree-sitter-casetalk.cson

Error: Cannot find module './build/Release/tree_sitter_CaseTalk_binding'
Require stack:
- /Users/marcowobben 1/.atom/packages/language-casetalk/node_modules/tree-sitter-casetalk/index.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/language-casetalk/node_modules/tree-sitter-casetalk/index.js:2:20)
    at /packages/language-casetalk/node_modules/tree-sitter-casetalk/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:696987)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3454686)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:361047)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360888
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:582968
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /packages/language-casetalk/grammars/tree-sitter-casetalk.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
api-workbench 0.8.48 
busy-signal 2.0.1 
intentions 1.1.5 
language-casetalk 0.3.1 
language-vba 0.2.5 
linter 3.1.1 
linter-ui-default 2.1.2 
```

**Comment by bcp-software** [comment]
This issue seems to be related to a library used inside Atom which fails when a path contains a whitespace. As soon as that was fixed, the issue dissappeared.
